### ISSUE TITLE
[BUG] Issues with Economies implementations and PicoJobs hooking

### ISSUE THREAD

**Issue by lukriq** [Picono435/PicoJobs#115]
**Describe the bug**
The newer versions of the plugin are not detecting EconomyPlus.

**To Reproduce**
1. If I start the server, the plugin is detecting EconomyPlus, so the salary pay-out is not working.

**Expected behavior**
That it detects EconomyPlus.

**Screenshots and Logs**
If it not detects EconomyPlus:

2 economy implementations successfully registered!

If it detects EconomyPlus:

1 economy implementations successfully registered! ( It just detects only Vault)

**Software Details:**
 - Server Software: [e.g. Spigot]
 - Server Software Version [e.g. 1.17.1]
 - Plugin Version [e.g. v58e0ddd-DEV (Currently, because it works with this version)]
 - Java Version: [e.g.  Java JRE 16]

**Additional context**

**Comment by Picono435** [comment]
A fix was implemented for this issue, please try with the latest DEV build. If this issue persists make sure to re-open this issue or create another one.
