### ISSUE TITLE
[SUGGESTION] Add default TAG in the configuration

### ISSUE THREAD

**Issue by lukriq** [Picono435/PicoJobs#116]
**Is your feature request related to a problem? Please describe.** and **Describe the solution you'd like**
Yes, I want to display the current Job of a player in the scoreboard with the placeholder %jobplayer_job%, but in the Jobs GUI if setted up the displaynames for the jobs "TONDACRAFT: Hunter", but if I put the placeholder in the scoreboard it also displays "TONDACRAFT: Hunter", but I want that in the scoreboard it only displays "Hunter".

**Describe alternatives you've considered**
- Add default TAG in the configuration

**Additional context**
None

**Comment by Picono435** [comment]
This suggestion was added in the latest DEV build, errors may occur, if you have anything else to say to tell about this issue make sure to re-open it or create another one.
