### ISSUE TITLE
[SUGGESTION] Add an item payment!

### ISSUE THREAD

**Issue by Aquamonk** [Picono435/PicoJobs#129]
**Is your feature request related to a problem? Please describe.**
Not a problem

**Describe the solution you'd like**
It would be good an item payment reward

**Describe alternatives you've considered**
A command to reward for example, or just an item option

**Additional context**
Thanks!

**Comment by Picono435** [comment]
This is now added in 1.0-beta-6. You can check the Wiki for more information on how to use it.
