### ISSUE TITLE
Filling bucket error

### ISSUE THREAD

**Issue by Karelidas** [Picono435/PicoJobs#14]
Hello sir,
I have an issue on my private server, players with permission (picojobs.use.basic) and also players with OP trigger an error in console. When they try to pick up water or lava (even milk from cow) with empty bucket, then console pops up this error:
[Report.txt](https://github.com/Picono435/PicoJobs/files/5958345/Report.txt)

10.02.2021 13:51:58 [SEVERE] Could not pass event PlayerBucketFillEvent to PicoJobs v1.0-beta-1ba
10.02.2021 13:51:58 org.bukkit.event.EventException
10.02.2021 13:51:58 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
10.02.2021 13:51:58 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
10.02.2021 13:51:58 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
10.02.2021 13:51:58 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
10.02.2021 13:51:58 	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.getPlayerBucketEvent(CraftEventFactory.java:162) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
10.02.2021 13:51:58 	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerBucketFillEvent(CraftEventFactory.java:139) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
10.02.2021 13:51:58 	at net.minecraft.server.v1_8_R3.ItemBucket.a(ItemBucket.java:57) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
10.02.2021 13:51:58 	at net.minecraft.server.v1_8_R3.ItemStack.a(ItemStack.java:234) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
10.02.2021 13:51:58 	at net.minecraft.server.v1_8_R3.PlayerInteractManager.useItem(PlayerInteractManager.java:370) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
10.02.2021 13:51:58 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:701) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
10.02.2021 13:51:58 	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
10.02.2021 13:51:58 	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
10.02.2021 13:51:58 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
10.02.2021 13:51:58 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_281]
10.02.2021 13:51:58 	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_281]
10.02.2021 13:51:58 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
10.02.2021 13:51:58 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:673) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
10.02.2021 13:51:58 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
10.02.2021 13:51:58 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:629) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
10.02.2021 13:51:58 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:537) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
10.02.2021 13:51:58 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
10.02.2021 13:51:58 Caused by: java.lang.NoSuchMethodError: org.bukkit.event.player.PlayerBucketFillEvent.getBlock()Lorg/bukkit/block/Block;
10.02.2021 13:51:58 	at com.gmail.picono435.picojobs.listeners.jobs.MilkListener.onTakeMilk(MilkListener.java:28) ~[?:?]
10.02.2021 13:51:58 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
10.02.2021 13:51:58 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
10.02.2021 13:51:58 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
10.02.2021 13:51:58 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281]
10.02.2021 13:51:58 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-18fbb24]
10.02.2021 13:51:58 	... 20 more

Server: craftbukkit-1.8.8-R0.1-SNAPSHOT-latest

Thank you sir for your time.
If you need provide something more, do not hesitate to ask.
Have a good day.

**Comment by Karelidas** [comment]
Newest version of PaperSpigot 1.12.2 do the same.

**Comment by Picono435** [comment]
Fixed issue in the  1.0-beta-1bb version. Please update your plugin, if this issue persists be free to re-open this issue or create another one.
