### ISSUE TITLE
[BUG] Seeds not recognized by the plugin.

### ISSUE THREAD

**Issue by keithphilippe** [Picono435/PicoJobs#144]
**Describe the bug**
I tried making a Farmer Job. So I whitelisted several items:
- minecraft: wheat_seeds, minecraft:wheat, minecraft:cocoa_beans, minecraft:cocoa_beans, minecraft:pumpkin_seeds, minecraft:melon_seeds, minecraft:nether_wart, minecraft:sugar_cane, minecraft:cactus, minecraft:sweet_berries, minecraft:beetroot, minecraft:potato, minecraft:carrot, minecraft:beetroot_seeds
- How will the job work? - By breaking seeds. I've also tried changing the type to place. It still doesn't work also.

Wheat seeds, beetroot seeds, cactus, carrots, and potatoes are not being recognized as blocks, so they aren't able to fulfill the job requirements. In contrary, sugarcanes are being recognized.

**To Reproduce**
1. Install the plugin
2. Change type to "break"
4. Whitelist items mentioned above
5. Plant the following whitelisted items
6. Break/place the mentioned items.
7. Check /jobs if there are blocks destroyed/placed.

**Expected behavior**
I expected the plugin to recognize different types of seeds to be recognized by breaking/placing them in the farmland.

**Screenshots and Logs**
None.

**Software Details:**
 - Server Software: PaperSpigot
 - Server Software Version: Paper 1.18.1
 - Plugin Version [e.g. 1.0-beta-1b, 1.0-beta-1bc]
 - Java Version: [e.g.  Version 8 Update 28)

**Additional context**
None.

**Comment by Picono435** [comment]
Thank you for reporting this issue, I will work on a fix for this issue asap.

**Comment by Picono435** [comment]
Fixed issue in the latest commit, thank you for reporting it. Be free to create another issue or re-open this one if the issue persists.
