### ISSUE TITLE
Trees are only one of all trees[BUG] 

### ISSUE THREAD

**Issue by editon96** [Picono435/PicoJobs#164]
So you run to the world whant to make a job /job then Treecutter after that we go to a tree, 
tippe again /job. But that dosnt count. Only Oak are "trees" pls change that!

**To Reproduce**
1. Go to 'Go to you server'
2. Tipe in Chat '/job'
3. Give the Job Woodcutter
4. go to a tree thats not oak
5. See error because thats not a tree

**Software Details:**
 - Server Software: [Pupur 1.18.1 (1547)]
 - Plugin Version [PicoJobs 1.0-beta-5 - Support for 1.18]
 - Java Version: 17

**Comment by Picono435** [comment]
Can you send me your jobs.yml?

**Comment by editon96** [comment]
[jobs.zip](https://github.com/Picono435/PicoJobs/files/8052223/jobs.zip)
[jobs.zip](https://github.com/Picono435/PicoJobs/files/8052226/jobs.zip)

I hope you have the file now.

**Comment by Picono435** [comment]
Hello this issue was not able to be reproducable. I did forget to add spruce wood if that is the case... You can add it yourself in the config here: 
![image](https://user-images.githubusercontent.com/57836766/156857611-07c488fe-eacf-4e17-bd4f-624021f309e1.png)

**Comment by Picono435** [comment]
Also it might be because you are in a old version if that's the case change the IDs in the whitelist.

**Comment by editon96** [comment]
thanks that worked
