### ISSUE TITLE
[SUGGESTION] Vault version

### ISSUE THREAD

**Issue by TheSupremeBoss** [Picono435/PicoJobs#170]
He tells me he needs Vault.
But Vault is in a previous version of the game as I do.

**Comment by Picono435** [comment]
Hello, so the plugin itself only requires VAULT if you want to connect the plugin to a economy plugin like Essentials. Also Vault should work in 1.18, even though it says it was only tested in 1.17. Let me know if any issue happens :).

**Comment by Picono435** [comment]
As the author of this issue did not answer this issue will be closed until further notice.
