### ISSUE TITLE
[SUGGESTION] Reformat the way whitelist works for multiple job types

### ISSUE THREAD

**Issue by FHaisal** [Picono435/PicoJobs#174]
**Is your feature request related to a problem? Please describe.**
Currently the `whitelist` works only for job types that share the same or similar whitelist values. Which means you can't have a job type of `SHEAR` and `BREAK`, because `SHEAR` only expects color types, so it throws an error when you add a block type.

**Describe the solution you'd like**
Could a solution like this be added:
```
whitelist:
  shear:
  - RED
  break:
  - hay_block 
```

This way you can specify specific object types for that job type

**Comment by Picono435** [comment]
This feature was added in the latest commit, if for some reason there is something wrong with it make sure to re-open this issue or create another one.
