### ISSUE TITLE
[BUG] MYSQL - Does not synchronize using it in multiserver

### ISSUE THREAD

**Issue by aleexgheorghe** [Picono435/PicoJobs#184]
**Describe the bug**
I am using PicoJobs on my Survival server which has more than 10 split servers. I have never had any problems with data synchronization (no matter mysql, mongo or redis). Everything has always worked fine for me. Using PicoJobs it's like the data is saved instantly but it doesn't work at all well on some of the servers, it's like it loses and/or doesn't read the data well. 

I would like to come up with a solution, either by reading the data every time a player enters the server or saving it when they leave the server. I come from using Jobs Reborn and it worked correctly. 

**To Reproduce**
I have bothered to record a video that shows how to reproduce it, the only thing I do is switching servers and running the jobs command with the phpmyadmin checking that it is updated. You can see it in the video https://youtu.be/VhjeVYODktM.

**Expected behavior**
The player's data must be synchronized each time he/she logs on and off the server.

**Software Details:**
 - Server Software: Paper
 - Server Software Version: 1.17.1
 - Plugin Version: Last build
 - Java Version: 17

**Comment by Picono435** [comment]
The mod saves data in the memory so if you change something in the phpmyadmin it will only update when you delete that memory. I might do something like when you leave the server it clears all the saved data in the memory from that user.

**Comment by aleexgheorghe** [comment]
I would really appreciate it! It would be a great help for all users who use the plugin in multiserver mode (you can implement a setting for it in case it affects database connections).

**Comment by aleexgheorghe** [comment]
Hello!

Do you know anything about this? This setting is something essential for my modality or servers using it multiserver.

Thank you very much.

**Comment by Picono435** [comment]
The latest commit added this feature please test it and let me know if fulfils your needs. You can download it [here](https://github.com/Picono435/PicoJobs/actions/runs/2110402214).

**Comment by aleexgheorghe** [comment]
Hi @Picono435 !

I hope you had an awesome day. I just updated it on two servers and apparently it didn't work for me. Still using the cache, in your test environment did it work fine?

[Builds.zip](https://github.com/Picono435/PicoJobs/files/8446053/Builds.zip) This is what I downloaded and updated the config by hand and set the cache option to TRUE.

Thank you very much, I am here to test everything you tell me. Thank you very much, I'm here to try everything you tell me.

**Comment by Picono435** [comment]
So if you go between servers the data is still not updated?

**Comment by aleexgheorghe** [comment]
Thank you for your reply,

I will check it in more detail if you wish, but at a glance the same thing is still happening.

**Comment by Picono435** [comment]
Hello sorry, I actually misspelt something, everything should work now.  I did test it in a local server and it seemed to be working, please give me an update asap. [here](https://github.com/Picono435/PicoJobs/actions/runs/2115682056)

**Comment by aleexgheorghe** [comment]
Thank you very much @Picono435 ! It works correctly 👯

**Comment by Picono435** [comment]
I am glad it worked! If you have any further issues let me know on Discord.
