### ISSUE TITLE
[SUGGESTION] Binding a job to a region (WE)

### ISSUE THREAD

**Issue by Vinellon** [Picono435/PicoJobs#187]
**Binding a job to a WorldEdit region**
Make it so that the task can be taken and performed only in a certain region of WorldEdit.
For example, the lumberjack job only works in the "sawmill" region (automatically set when you enter, and removed when you leave).
I think this will be very convenient for creating "work zones"

**Comment by Picono435** [comment]
Hello, I think something like a work-zone-implementation would be good. Something like the economy-implementation but for work zones. I will for sure work on things like this.

**Comment by Picono435** [comment]
One year later this is now being worked on. If anyone has any plugin suggestions to be added make sure to let me know. As I'm writing this message the following plugins are supported: WorldGuard, GriefPrevention.

**Comment by Picono435** [comment]
This feature is marked as done but it hasn't been released yet as I am now working on different platform support. You can still download the version you want from GitHub actions and use a experimental build.
