### ISSUE TITLE
[SUGGESTION] Hex Codes and Placeholders

### ISSUE THREAD

**Issue by barannnnnns** [Picono435/PicoJobs#188]
For 1.16 and above hex codes can be supported. Using this color format will make the plugin look beautiful on the server. It will also introduce a new feature for the user.

Besides, adding placeholders would be useful in many ways. (For example: Servers with texture packs can perform different operations on these items. Or they can show information about the group they created...)

**Comment by Picono435** [comment]
Hello sorry, but what do you actually mean by placeholders in items? Do you mean custom NBT?

**Comment by barannnnnns** [comment]
No, I'm talking about using placeholders like %player% in item names.

**Comment by Picono435** [comment]
Everything suggested here should now be added to the plugin in the latest development builds.
