### ISSUE TITLE
[BUG] DUPE MONEY - IN AND OUT OF JOBS

### ISSUE THREAD

**Issue by aleexgheorghe** [Picono435/PicoJobs#194]
**Describe the bug**
Hello! Apparently several users have been reporting to me that many of my players keep taking advantage of it. When you exit and enter a job, the progress of this same job is reset and the user starts from the beginning.

For example, if the Hunter job has 40 levels (for example) the user goes up to level 10 and by exiting and entering he earns money super fast since the low levels are easy and a lot of money is earned.

**To Reproduce**
1. You enter a job
2. You work your way up to X advancement.
3. You claim the money, get out, and get back in.
4. You do the same thing and the money earned is insane.

**Expected behavior**
How can this be solved? The progress of each job should be saved per user, for example, if the user is in the hunter job and has been playing for 10 days, if he/she quits, he/she should not lose the progress. It would be the most "professional".

**Comment by Picono435** [comment]
The latest commit added this feature please test it and let me know if fulfils your needs. You can download it [here](https://github.com/Picono435/PicoJobs/actions/runs/2212574091).
