### ISSUE TITLE
[BUG] Cow milking console spam

### ISSUE THREAD

**Issue by mario414x** [Picono435/PicoJobs#196]
Console starts spamming when a player milk a cow no matter if he is in survival or creative mode

**To Reproduce**
1. Milk a cow

Error: https://pastebin.com/T0s9Ernq

**Software Details:**
 - Server Software: Paperspigot
 - Server Software Version: paper-1.16.5-794
 - Plugin Version: PicoJobs-1.0-beta-6a
 - Java Version: openjdk 16.0.1 2021-04-20

**Additional context**

**Comment by Picono435** [comment]
This issue should be fixed in the latest development builds.
