### ISSUE TITLE
[BUG] Salary Cooldown reseting when server closes

### ISSUE THREAD

**Issue by rlcoldx** [Picono435/PicoJobs#210]
Quando sacamos o salario e começa a contar o "salary-cooldown" está contando certinho. Mas se o servidor for reiniciado o tempo é resetado e eu posso sacar novamente. Ou seja, não está salvando o tempo de delay do saque. Então sempre que o servidor é reiniciado pode ser feito um saque novamente.

**Comment by Picono435** [comment]
This issue should be fixed in the latest experimental build. Thank you for reporting it.
