### ISSUE TITLE
[BUG] All info lines are logged as warns

### ISSUE THREAD

**Issue by RhythmicSys** [Picono435/PicoJobs#229]
**Describe the bug**
Lines that should be logged under `info` or similar, are logged under `warn` unnecessarily 

**To Reproduce**
1) Add plugin to plugin folder
2) Start server
3) View startup logs

**Expected behavior**
That the plugin would not warn for non-issues, but instead log as info

**Screenshots and Logs**
![image](https://user-images.githubusercontent.com/45906780/188286935-719a71bc-ad7b-4d22-8b44-a49022095ea5.png)

**Software Details:**
 - Server Software: `Purpur`
 - Server Software Version: `Current: git-Purpur-1771 (MC: 1.19.2)*`
 - Plugin Version: `1.0-beta-7a`
 - Java Version: 
 ```java
java 17.0.4 2022-07-19 LTS
Java(TM) SE Runtime Environment (build 17.0.4+11-LTS-179)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.4+11-LTS-179, mixed mode, sharing)
```

**Additional context**
Reading `[WARN] The plugin has loaded successfully` and `[WARN] You are on the latest version` is confusing

**Comment by Picono435** [comment]
This is actually something that should be changed. I will look into it.

**Comment by Picono435** [comment]
This issue has been fixed in the latest development build. Thank you for reporting it.
