### ISSUE TITLE
[BUG] Fix issue with crops not being counted with BREAK job type

### ISSUE THREAD

**Issue by EmilPetrakiev** [Picono435/PicoJobs#269]
The normal BREAK type job has problems with farming items. It would be great if the plugin has a HARVEST job type or something like that. If not at least add the possibility of the BREAK job type to count crops. (The only crop that it counts at the moment is wheat. All of the others are not detected when braked.)

I'm not sure if the BREAK job type not counting broken crops should be considered a bug.

**Comment by Picono435** [comment]
This issue is fixed in the latest DEV build which can now be downloaded in the GitHub Actions. For further help make sure to send a message on my Discord or feel free to respond again to the issue.
