### ISSUE TITLE
Issue: Bow

### ISSUE THREAD

**Issue by FreakyHydra** [Picono435/PicoJobs#27]
Job: Hunter
Issue Bow is not registered as a kill

**Comment by Picono435** [comment]
This issue is now under investigation, soon I will get back to you.

**Comment by Picono435** [comment]
The reason of the issue was identified and a fix for this issue will be added in the next update.

**Comment by Picono435** [comment]
Hi! After some tests I identified this issue is not a valid issue. Please try to explain more about your issue in order to us understand better what is causing your problem and what is the problem.

**Comment by Picono435** [comment]
This is not a valid issue, if you still are having problems with our plugin be free to re-open this issue or create a new one.
