### ISSUE TITLE
MySQL Create Tables error (-)

### ISSUE THREAD

**Issue by DqnyLux** [Picono435/PicoJobs#277]
**Describe the bug**
When connecting to mysql, the plugin cannot create the tables because the table names have a (-) and it gives an error.

**Screenshots and Logs**
![image](https://user-images.githubusercontent.com/108638128/223360622-d71ebf01-e84e-405c-8a62-c19fde0f5e69.png)
![image](https://user-images.githubusercontent.com/108638128/223362195-c572fee2-8e8e-4af4-ba22-ac75794704d7.png)

**Software Details:**
 - Server Software: Purpur
 - Server Software Version: Purpur-1171 1.16.5
 - Plugin Version 1.0-beta-7a
 - Java Version: 16

**Additional context**
The problem is not with the mysql version since I tried with version 5.7.x and 8.0.
I also tried to test with MariaDB and it didn't let me either.

**Comment by Picono435** [comment]
I am sorry that you are having issues with our plugin unfortunately this issue does not have a fix in our side. Maybe replacing _ with - would fix your issue but that would require a major changing in the plugin which I do not have time to work on now. You can try to search more about this issue or follow the instructions I sent you in Discord on how maybe you can fix this issue in your side.

Thank you for reporting the issue and please let me know if the issue persists in Discord.
