### ISSUE TITLE
[BUG] MongoDB Error

### ISSUE THREAD

**Issue by ghost** [Picono435/PicoJobs#286]
**Describe the bug**
The plugin starts and it connects to MongoDB but nothing works after that.

**To Reproduce**
Start the Server and watch
**Expected behavior**

**Screenshots and Logs**
Connecting to MongoDB
![image](https://user-images.githubusercontent.com/105009484/226710006-c1d982b6-9f97-436e-9131-59a402027e34.png)

Error:
![image](https://user-images.githubusercontent.com/105009484/226710302-6d4e16d9-2de6-4308-ae2d-2b0fbc32f756.png)

**Software Details:**
 - Server Software: PurPur
 - Server Software Version: Current: git-Purpur-1933 (MC: 1.19.3)*
 - Plugin Version [LATEST]
 - Java Version: 17

**Comment by Picono435** [comment]
This issue is fixed in the latest DEV build which can now be downloaded in the GitHub Actions. For further help make sure to send a message on my Discord or feel free to respond again to the issue.
