### ISSUE TITLE
Question about salary

### ISSUE THREAD

**Issue by Mientos110** [Picono435/PicoJobs#346]
Hey! 
I have a question like in the title. I'd like to get payment not by cash or something, but in item. I mean, economy on my server is based on two items (the 1st one is normal cash, the second is better cash). And now: How to set the payment that gives players X amount of block? (The block is skeleton_skull)
Probably it's somewhere in Your Wiki, but I can't find it

**Comment by Picono435** [comment]
You can find that in the wiki :)
https://github.com/Picono435/PicoJobs/wiki/Economy-Types
If you need further help send me a message over on discord.

**Comment by Mientos110** [comment]
Ok, I'll ask you  on discord. But I don't see Your discord anywhere xD

**Comment by Picono435** [comment]
https://discord.com/invite/wQj53Hy
