### ISSUE TITLE
[BUG] Crafts using shift click don't count

### ISSUE THREAD

**Issue by Senteris** [Picono435/PicoJobs#347]
**Describe the bug**
Crafts using shift+click are not recognized properly

**To Reproduce**
1. Start a job asking you to craft a certain amount of items; note the required amount
2. Take 64 blocks of wood
3. Turn them directly into 4x64 planks using shift+click when doing the craft
4. You should see that the required amount only has been reduced by 4 units instead of 64

**Expected behavior**
It should have counted all the 64 wood blocks that have been used during the process.

**Software Details:**
 - Server Software: [PaperSpigot]
 - Server Software Version [PaperSpigot 1.20.1, build 97]
 - Plugin Version [1.0-beta-7a]
 - Java Version: 17

**Comment by Picono435** [comment]
This issue should be fixed in the multiplatform branch which will be released very soon.
