### ISSUE TITLE
[BUG] Can't run commands (SOLVED)

### ISSUE THREAD

**Issue by LegitMariosGR** [Picono435/PicoJobs#361]
**Describe the bug**
I have the 1.0-pre for mc 1.21 on spigot and when I do a command like /jobs or /jobs or /jobs salary, an error saying "An internal error occured while attempting to perform this command" and it doesn't work. However, /jobsadmin commands work

**To Reproduce**
1. Have a server running 1.21 spigot with 1.0-pre
2. Run /jobs command
3. See error

**Expected behavior**
I expect maybe a menu to pop up, or something in the chat

**Screenshots and Logs**
![image](https://github.com/user-attachments/assets/de13666e-22b9-44d2-a872-0cf32bcd76e4)
![image](https://github.com/user-attachments/assets/d2db04a2-3bb3-4ddf-9c8d-25affd2b9aca)
![image](https://github.com/user-attachments/assets/7f44499b-df06-49d4-bcf8-1b6747f3364d)

**Software Details:**
 - Server Software: Spigot
 - Server Software Version Spigot 1.21
 - Plugin Version 1.0-pre
 - Java Version: Java 21

**Additional context**
Im running it in aternos with these plugins too:

![image](https://github.com/user-attachments/assets/1af6471b-e129-4d94-81da-be03990d7b7f)

**Comment by Picono435** [comment]
Is there any reason why you are not running in version 1.0-pre already? We currently only support the latest version of the plugin.

**Comment by LegitMariosGR** [comment]
I did at first and there was the same issue, I thought that maybe going to an older version would help but it didn't

**Comment by LegitMariosGR** [comment]
I'm running it now with the latest version and the same error occurs, I have attached one more picture if that helps.

**Comment by LegitMariosGR** [comment]
I just changed the server version to paper and it now perfectly works, why didnt it work in spigot tho?
