### ISSUE TITLE
[SUGGESTION] - Two jobs type in the same job

### ISSUE THREAD

**Issue by jhefersongambet** [Picono435/PicoJobs#41]
Add the possibility to insert two actions in the types of jobs

example =

type: ["break", "place"]

**Comment by Picono435** [comment]
I will start thinking of a simple way to do this and this feature will probably be added in a future version before the 1.0 release.

**Comment by Picono435** [comment]
Implemented as an experimental feature in 1.0-beta-3c, thank you for the suggestion.
