### ISSUE TITLE
[BUG] JitPack build error

### ISSUE THREAD

**Issue by Medialo** [Picono435/PicoJobs#78]
Hi,

I am currently using and integrating picojobs into my plugin, and I'm stuck at version 1.0-beta-2a because it seems to have an error with the build on jitpack since version 1.0-beta-3.
Is this just a jitpack error?

Medialo

**Comment by Picono435** [comment]
Hello, may I know what is the error?

**Comment by Picono435** [comment]
I will try and check what is happenning.

**Comment by Picono435** [comment]
I identified the issue and I am now trying to fix it. There will only be a fix available tomorrow. The two commits above are two failed tries to make it work... I am getting near to it and I will get to you asap.

**Comment by Picono435** [comment]
This issue was fixed in the latest commit (850bb848bd), if you are still having issues create another ticket or re-create this one. Temporarily set the version to 850bb848bd while the plugin does not update.

**Comment by Picono435** [comment]
The newest version 1.0-beta-3d now includes a fix for this issue, thank you for reporting it.
